default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>

development:
  <<: *default
  database: managers_recruitment_development

test:
  <<: *default
  database: managers_recruitment_test

production:
  primary: &primary_production
    <<: *default
    database: managers_recruitment_production
    username: managers_recruitment
    password: <%= ENV["DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: managers_recruitment_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: managers_recruitment_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: managers_recruitment_production_cable
    migrations_paths: db/cable_migrate
