default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if ENV["RAILS_ENV"] %>
  host: <%= Rails.application.credentials.dig(:database, :host) %>
  username: postgres
  password: postgres
  <% end %>

development:
  <<: *default
  database: managers_recruitment_development

test:
  <<: *default
  database: managers_recruitment_test

production:
  primary: &primary_production
    <<: *default
    database: <%= Rails.application.credentials.dig(:database, :name) %>
    username: <%= Rails.application.credentials.dig(:database, :username) %>
    password: <%= Rails.application.credentials.dig(:database, :password) %>
    host: <%= Rails.application.credentials.dig(:database, :host) %>
    port: <%= Rails.application.credentials.dig(:database, :port) || 5432 %>
  cache:
    <<: *primary_production
    database: managers_recruitment_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: managers_recruitment_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: managers_recruitment_production_cable
    migrations_paths: db/cable_migrate
